In [17]:
#Is there a relationship between the percentage of households using cars for transportation and the percentage of museums classified as art museums in North Carolina counties?

In [18]:
pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\allis\anaconda3\lib\site-packages (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import os
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv, find_dotenv

In [20]:
load_dotenv()

False

In [21]:
api_key = os.getenv("CENSUS_API_KEY")

In [22]:
print(api_key)
print("37d5985ad46bc17215096d5b16589ea3d45dada8")

None
37d5985ad46bc17215096d5b16589ea3d45dada8

In [33]:
url = f"https://api.census.gov/data/2024/acs/acs1?get=NAME,B01001_001E&for=county:*&in=state:37&key=37d5985ad46bc17215096d5b16589ea3d45dada8"

In [34]:
response = requests.get(url)

In [35]:
response.text

'[["NAME","B01001_001E","state","county"],\n["Alamance County, North Carolina","183040","37","001"],\n["Brunswick County, North Carolina","167112","37","019"],\n["Buncombe County, North Carolina","279210","37","021"],\n["Burke County, North Carolina","88545","37","023"],\n["Cabarrus County, North Carolina","244925","37","025"],\n["Caldwell County, North Carolina","80739","37","027"],\n["Carteret County, North Carolina","70259","37","031"],\n["Catawba County, North Carolina","167054","37","035"],\n["Chatham County, North Carolina","83874","37","037"],\n["Cleveland County, North Carolina","102194","37","045"],\n["Craven County, North Carolina","104167","37","049"],\n["Cumberland County, North Carolina","338430","37","051"],\n["Davidson County, North Carolina","177809","37","057"],\n["Durham County, North Carolina","343628","37","063"],\n["Forsyth County, North Carolina","398143","37","067"],\n["Franklin County, North Carolina","79771","37","069"],\n["Gaston County, North Carolina","242010","37","071"],\n["Guilford County, North Carolina","558816","37","081"],\n["Harnett County, North Carolina","146096","37","085"],\n["Henderson County, North Carolina","120771","37","089"],\n["Iredell County, North Carolina","206361","37","097"],\n["Johnston County, North Carolina","249794","37","101"],\n["Lee County, North Carolina","68537","37","105"],\n["Lincoln County, North Carolina","97611","37","109"],\n["Mecklenburg County, North Carolina","1206285","37","119"],\n["Moore County, North Carolina","108417","37","125"],\n["Nash County, North Carolina","97990","37","127"],\n["New Hanover County, North Carolina","243333","37","129"],\n["Onslow County, North Carolina","212954","37","133"],\n["Orange County, North Carolina","152877","37","135"],\n["Pender County, North Carolina","70077","37","141"],\n["Pitt County, North Carolina","180783","37","147"],\n["Randolph County, North Carolina","148389","37","151"],\n["Robeson County, North Carolina","118624","37","155"],\n["Rockingham County, North Carolina","93517","37","157"],\n["Rowan County, North Carolina","153384","37","159"],\n["Rutherford County, North Carolina","65587","37","161"],\n["Stanly County, North Carolina","67326","37","167"],\n["Surry County, North Carolina","71547","37","171"],\n["Union County, North Carolina","263386","37","179"],\n["Wake County, North Carolina","1232444","37","183"],\n["Wayne County, North Carolina","120338","37","191"],\n["Wilkes County, North Carolina","66186","37","193"],\n["Wilson County, North Carolina","79958","37","195"]]'

In [36]:
data = response.json()

In [37]:
data

[['NAME', 'B01001_001E', 'state', 'county'],
 ['Alamance County, North Carolina', '183040', '37', '001'],
 ['Brunswick County, North Carolina', '167112', '37', '019'],
 ['Buncombe County, North Carolina', '279210', '37', '021'],
 ['Burke County, North Carolina', '88545', '37', '023'],
 ['Cabarrus County, North Carolina', '244925', '37', '025'],
 ['Caldwell County, North Carolina', '80739', '37', '027'],
 ['Carteret County, North Carolina', '70259', '37', '031'],
 ['Catawba County, North Carolina', '167054', '37', '035'],
 ['Chatham County, North Carolina', '83874', '37', '037'],
 ['Cleveland County, North Carolina', '102194', '37', '045'],
 ['Craven County, North Carolina', '104167', '37', '049'],
 ['Cumberland County, North Carolina', '338430', '37', '051'],
 ['Davidson County, North Carolina', '177809', '37', '057'],
 ['Durham County, North Carolina', '343628', '37', '063'],
 ['Forsyth County, North Carolina', '398143', '37', '067'],
 ['Franklin County, North Carolina', '79771', '37', '069'],
 ['Gaston County, North Carolina', '242010', '37', '071'],
 ['Guilford County, North Carolina', '558816', '37', '081'],
 ['Harnett County, North Carolina', '146096', '37', '085'],
 ['Henderson County, North Carolina', '120771', '37', '089'],
 ['Iredell County, North Carolina', '206361', '37', '097'],
 ['Johnston County, North Carolina', '249794', '37', '101'],
 ['Lee County, North Carolina', '68537', '37', '105'],
 ['Lincoln County, North Carolina', '97611', '37', '109'],
 ['Mecklenburg County, North Carolina', '1206285', '37', '119'],
 ['Moore County, North Carolina', '108417', '37', '125'],
 ['Nash County, North Carolina', '97990', '37', '127'],
 ['New Hanover County, North Carolina', '243333', '37', '129'],
 ['Onslow County, North Carolina', '212954', '37', '133'],
 ['Orange County, North Carolina', '152877', '37', '135'],
 ['Pender County, North Carolina', '70077', '37', '141'],
 ['Pitt County, North Carolina', '180783', '37', '147'],
 ['Randolph County, North Carolina', '148389', '37', '151'],
 ['Robeson County, North Carolina', '118624', '37', '155'],
 ['Rockingham County, North Carolina', '93517', '37', '157'],
 ['Rowan County, North Carolina', '153384', '37', '159'],
 ['Rutherford County, North Carolina', '65587', '37', '161'],
 ['Stanly County, North Carolina', '67326', '37', '167'],
 ['Surry County, North Carolina', '71547', '37', '171'],
 ['Union County, North Carolina', '263386', '37', '179'],
 ['Wake County, North Carolina', '1232444', '37', '183'],
 ['Wayne County, North Carolina', '120338', '37', '191'],
 ['Wilkes County, North Carolina', '66186', '37', '193'],
 ['Wilson County, North Carolina', '79958', '37', '195']]

In [42]:
dfcsv = pd.read_csv(r"C:\Users\allis\Downloads\nc_county_art_pct.csv")

dfcsv.head()

      county  percent_art_museum  museum_count  art_museum_count
0   Alamance                 0.0            11                 0
1  Alexander                 0.0             3                 0
2  Alleghany                 0.0             2                 0
3      Anson                 0.0             2                 0
4       Ashe                 0.0             4                 0

In [ ]:
variables = ",".join([
    "NAME",            # County name
    "B01003_001E",     # Total population
    "B08141_001E",     # Total: Means of Transportation to Work by Vehicles Available (People that drive)
    "B08141_016E",     # Estimate!!Total:!!Public transportation:
    "B08141_017E",     # Estimate!!Total:!!Public transportation:!!No vehicle available
    "B08141_021E",     #Estimate!!Total:!!Walked:

])

In [39]:
df = pd.DataFrame(data[1:], columns=data[0])

In [43]:
df.head()

                               NAME B01001_001E state county
0   Alamance County, North Carolina      183040    37    001
1  Brunswick County, North Carolina      167112    37    019
2   Buncombe County, North Carolina      279210    37    021
3      Burke County, North Carolina       88545    37    023
4   Cabarrus County, North Carolina      244925    37    025

In [55]:
County_names = list(df['NAME'])
counties = list(dfcsv['county'])

print(counties)
print(County_names)

['Alamance', 'Alexander', 'Alleghany', 'Anson', 'Ashe', 'Avery', 'Beaufort', 'Bertie', 'Bladen', 'Brunswick', 'Buncombe', 'Burke', 'Cabarrus', 'Caldwell', 'Carteret', 'Caswell', 'Catawba', 'Chatham', 'Cherokee', 'Chowan', 'Clay', 'Cleveland', 'Columbus', 'Craven', 'Cumberland', 'Currituck', 'Dare', 'Davidson', 'Davie', 'Duplin', 'Durham', 'Edgecombe', 'Forsyth', 'Franklin', 'Gaston', 'Gates', 'Graham', 'Granville', 'Greene', 'Guilford', 'Halifax', 'Harnett', 'Haywood', 'Henderson', 'Hertford', 'Hoke', 'Hyde', 'Iredell', 'Jackson', 'Johnston', 'Jones', 'Lee', 'Lenoir', 'Lincoln', 'Macon', 'Madison', 'Martin', 'McDowell', 'Mecklenburg', 'Mitchell', 'Montgomery', 'Moore', 'Nash', 'New Hanover', 'Northampton', 'Onslow', 'Orange', 'Pamlico', 'Pasquotank', 'Pender', 'Perquimans', 'Person', 'Pitt', 'Polk', 'Randolph', 'Richmond', 'Robeson', 'Rockingham', 'Rowan', 'Rutherford', 'Sampson', 'Scotland', 'Stanly', 'Stokes', 'Surry', 'Swain', 'Transylvania', 'Union', 'Vance', 'Wake', 'Warren', 'Washington', 'Watauga', 'Wayne', 'Wilkes', 'Wilson', 'Yadkin', 'Yancey']
['Alamance County, North Carolina', 'Brunswick County, North Carolina', 'Buncombe County, North Carolina', 'Burke County, North Carolina', 'Cabarrus County, North Carolina', 'Caldwell County, North Carolina', 'Carteret County, North Carolina', 'Catawba County, North Carolina', 'Chatham County, North Carolina', 'Cleveland County, North Carolina', 'Craven County, North Carolina', 'Cumberland County, North Carolina', 'Davidson County, North Carolina', 'Durham County, North Carolina', 'Forsyth County, North Carolina', 'Franklin County, North Carolina', 'Gaston County, North Carolina', 'Guilford County, North Carolina', 'Harnett County, North Carolina', 'Henderson County, North Carolina', 'Iredell County, North Carolina', 'Johnston County, North Carolina', 'Lee County, North Carolina', 'Lincoln County, North Carolina', 'Mecklenburg County, North Carolina', 'Moore County, North Carolina', 'Nash County, North Carolina', 'New Hanover County, North Carolina', 'Onslow County, North Carolina', 'Orange County, North Carolina', 'Pender County, North Carolina', 'Pitt County, North Carolina', 'Randolph County, North Carolina', 'Robeson County, North Carolina', 'Rockingham County, North Carolina', 'Rowan County, North Carolina', 'Rutherford County, North Carolina', 'Stanly County, North Carolina', 'Surry County, North Carolina', 'Union County, North Carolina', 'Wake County, North Carolina', 'Wayne County, North Carolina', 'Wilkes County, North Carolina', 'Wilson County, North Carolina']

In [63]:

filtered_list = [item.split(" County")[0] for item in County_names]


filtered_list2 = [item for item in counties if item in filtered_list]


print("Original list:", counties)
print("Filtered list:", filtered_list)
print(counties)
print(filtered_list2)

Original list: ['Alamance', 'Alexander', 'Alleghany', 'Anson', 'Ashe', 'Avery', 'Beaufort', 'Bertie', 'Bladen', 'Brunswick', 'Buncombe', 'Burke', 'Cabarrus', 'Caldwell', 'Carteret', 'Caswell', 'Catawba', 'Chatham', 'Cherokee', 'Chowan', 'Clay', 'Cleveland', 'Columbus', 'Craven', 'Cumberland', 'Currituck', 'Dare', 'Davidson', 'Davie', 'Duplin', 'Durham', 'Edgecombe', 'Forsyth', 'Franklin', 'Gaston', 'Gates', 'Graham', 'Granville', 'Greene', 'Guilford', 'Halifax', 'Harnett', 'Haywood', 'Henderson', 'Hertford', 'Hoke', 'Hyde', 'Iredell', 'Jackson', 'Johnston', 'Jones', 'Lee', 'Lenoir', 'Lincoln', 'Macon', 'Madison', 'Martin', 'McDowell', 'Mecklenburg', 'Mitchell', 'Montgomery', 'Moore', 'Nash', 'New Hanover', 'Northampton', 'Onslow', 'Orange', 'Pamlico', 'Pasquotank', 'Pender', 'Perquimans', 'Person', 'Pitt', 'Polk', 'Randolph', 'Richmond', 'Robeson', 'Rockingham', 'Rowan', 'Rutherford', 'Sampson', 'Scotland', 'Stanly', 'Stokes', 'Surry', 'Swain', 'Transylvania', 'Union', 'Vance', 'Wake', 'Warren', 'Washington', 'Watauga', 'Wayne', 'Wilkes', 'Wilson', 'Yadkin', 'Yancey']
Filtered list: ['Alamance', 'Brunswick', 'Buncombe', 'Burke', 'Cabarrus', 'Caldwell', 'Carteret', 'Catawba', 'Chatham', 'Cleveland', 'Craven', 'Cumberland', 'Davidson', 'Durham', 'Forsyth', 'Franklin', 'Gaston', 'Guilford', 'Harnett', 'Henderson', 'Iredell', 'Johnston', 'Lee', 'Lincoln', 'Mecklenburg', 'Moore', 'Nash', 'New Hanover', 'Onslow', 'Orange', 'Pender', 'Pitt', 'Randolph', 'Robeson', 'Rockingham', 'Rowan', 'Rutherford', 'Stanly', 'Surry', 'Union', 'Wake', 'Wayne', 'Wilkes', 'Wilson']
['Alamance', 'Alexander', 'Alleghany', 'Anson', 'Ashe', 'Avery', 'Beaufort', 'Bertie', 'Bladen', 'Brunswick', 'Buncombe', 'Burke', 'Cabarrus', 'Caldwell', 'Carteret', 'Caswell', 'Catawba', 'Chatham', 'Cherokee', 'Chowan', 'Clay', 'Cleveland', 'Columbus', 'Craven', 'Cumberland', 'Currituck', 'Dare', 'Davidson', 'Davie', 'Duplin', 'Durham', 'Edgecombe', 'Forsyth', 'Franklin', 'Gaston', 'Gates', 'Graham', 'Granville', 'Greene', 'Guilford', 'Halifax', 'Harnett', 'Haywood', 'Henderson', 'Hertford', 'Hoke', 'Hyde', 'Iredell', 'Jackson', 'Johnston', 'Jones', 'Lee', 'Lenoir', 'Lincoln', 'Macon', 'Madison', 'Martin', 'McDowell', 'Mecklenburg', 'Mitchell', 'Montgomery', 'Moore', 'Nash', 'New Hanover', 'Northampton', 'Onslow', 'Orange', 'Pamlico', 'Pasquotank', 'Pender', 'Perquimans', 'Person', 'Pitt', 'Polk', 'Randolph', 'Richmond', 'Robeson', 'Rockingham', 'Rowan', 'Rutherford', 'Sampson', 'Scotland', 'Stanly', 'Stokes', 'Surry', 'Swain', 'Transylvania', 'Union', 'Vance', 'Wake', 'Warren', 'Washington', 'Watauga', 'Wayne', 'Wilkes', 'Wilson', 'Yadkin', 'Yancey']
['Alamance', 'Brunswick', 'Buncombe', 'Burke', 'Cabarrus', 'Caldwell', 'Carteret', 'Catawba', 'Chatham', 'Cleveland', 'Craven', 'Cumberland', 'Davidson', 'Durham', 'Forsyth', 'Franklin', 'Gaston', 'Guilford', 'Harnett', 'Henderson', 'Iredell', 'Johnston', 'Lee', 'Lincoln', 'Mecklenburg', 'Moore', 'Nash', 'New Hanover', 'Onslow', 'Orange', 'Pender', 'Pitt', 'Randolph', 'Robeson', 'Rockingham', 'Rowan', 'Rutherford', 'Stanly', 'Surry', 'Union', 'Wake', 'Wayne', 'Wilkes', 'Wilson']

In [70]:
dfcsv_filtered = dfcsv[dfcsv['county'].isin(filtered_list)]

print(dfcsv_filtered)

len(dfcsv_filtered)

         county  percent_art_museum  museum_count  art_museum_count
0      Alamance                0.00            11                 0
9     Brunswick                0.00             7                 0
10     Buncombe                8.00            25                 2
11        Burke                0.00             9                 0
12     Cabarrus                0.00             8                 0
13     Caldwell               14.29             7                 1
14     Carteret                0.00             9                 0
16      Catawba                6.67            15                 1
17      Chatham               25.00             4                 1
21    Cleveland                0.00             7                 0
23       Craven                7.69            13                 1
24   Cumberland                5.26            19                 1
27     Davidson               14.29             7                 1
30       Durham               11.54            26                 3
32      Forsyth                9.68            31                 3
33     Franklin               33.33             3                 1
34       Gaston                7.69            13                 1
39     Guilford                4.65            43                 2
41      Harnett                0.00             9                 0
43    Henderson               16.67             6                 1
47      Iredell                0.00            14                 0
49     Johnston                0.00             8                 0
51          Lee                0.00             3                 0
53      Lincoln                0.00             4                 0
58  Mecklenburg                6.78            59                 4
61        Moore                9.09            11                 1
62         Nash                0.00             2                 0
63  New Hanover                6.67            30                 2
65       Onslow                0.00            13                 0
66       Orange                0.00            27                 0
69       Pender                0.00             4                 0
72         Pitt               14.29            14                 2
74     Randolph                7.14            14                 1
76      Robeson                0.00             9                 0
77   Rockingham                0.00             7                 0
78        Rowan                8.00            25                 2
79   Rutherford                0.00             9                 0
82       Stanly               14.29             7                 1
84        Surry                0.00             5                 0
87        Union                0.00             9                 0
89         Wake                6.17            81                 5
93        Wayne                0.00             7                 0
94       Wilkes               20.00             5                 1
95       Wilson                0.00            11                 0

44

In [68]:
len(df)

44

In [ ]:
numeric_cols = [
    #"NAME",            # County name
    "B01003_001E",     # Total population
    "B08141_001E",     # Total: Means of Transportation to Work by Vehicles Available (People that drive)
    "B08141_016E",     # Estimate!!Total:!!Public transportation:
    "B08141_017E",     # Estimate!!Total:!!Public transportation:!!No vehicle available
    "B08141_021E"      #Estimate!!Total:!!Walked:
]

#for col in numeric_cols:
#   df[col] = pd.to_numeric(df[col], errors="coerce") # coerce -> If something cannot be converted to a number, don’t crash. Instead, turn it into NaN.

df = df.rename(columns={
    #"NAME": "County_Name",
    "B01003_001E": "Total_Population",
    "B08141_001E": "Total Transportation By Vehicles Available",
    "B08141_016E": "Total Public Transportation",
    "B08141_017E": "No_Vehicle_Available",
    "B08141_021E": "Walked"
})

df.head()

NameError: name 'df' is not defined

In [ ]:
df.isnull().sum()

NAME           0
B01001_001E    0
state          0
county         0
dtype: int64

In [ ]:
plt.figure(figsize=(8,6))
sns.scatterplot(data=df, x="Total Public Transportation", y="Walked")
plt.title("Total Public Transportation vs Walked to Work (NC Counties)")
plt.xlabel("Total Public Transportation")
plt.ylabel("Walked to Work")
plt.show()

ValueError: Could not interpret value `Total Public Transportation` for `x`. An entry with this name does not appear in `data`.

In [ ]:
dfboth = pd.merge(df, dfcsv, on="NAME") #combines the data sets using the shared variable of county name so I can use variables from both for my visualization

In [ ]:
plt.figure(figsize=(8,6))
sns.scatterplot(data=dfboth, x="Total Public Transportation", y="Walked")
plt.title("Total Public Transportation vs Walked to Work (NC Counties)")
plt.xlabel("Total Public Transportation")
plt.ylabel("Walked to Work")
plt.show()

In [ ]:
plt.figure(figsize=(8,6))
sns.histplot(df[""], bins=20)
plt.title("")
plt.xlabel("")
plt.ylabel("")
plt.show()